<?php

class MySettingsPage
{
    /**
     * Holds the values to be used in the fields callbacks
     */
    private $options;

    /**
     * Start up
     */
    public function __construct()
    {
        add_action( 'admin_menu', array( $this, 'add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'page_init' ) );
    }

    /**
     * Add options page
     */
    public function add_plugin_page()
    {
        // This page will be under "Settings"
        add_options_page(
            'Settings Admin', 
            'Plugin Lock Settings', 
            'manage_options', 
            'my-setting-admin', 
            array( $this, 'create_admin_page' )
        );
    }




    /**
     * Options page callback
     */
    public function create_admin_page()
    {
        // Set class property
        $this->options = get_option( 'my_option_name' );
        ?>
        <div class="wrap">
            <h1>Plugin Lock Settings</h1>
            <?php
                // This prints out all hidden setting fields
                settings_fields( 'my_option_group' );
                do_settings_sections( 'my-setting-admin' );
				
				global $wpdb;
// this adds the prefix which is set by the user upon instillation of wordpress
$table_name = $wpdb->prefix . "wppluginlock";
// this will get the data from your table
$retrieve_data = $wpdb->get_results( "SELECT * FROM $table_name" );
?>
<h2>Plugin Upload </h2>
<div id="pluginuploadclass">
<form id="pluginzip_upload" name="pluginzip_upload" method="post" action="" enctype="multipart/form-data">
	<?php wp_nonce_field( 'pluginzip', 'pluginzip_nonce' ); ?>
    <label class="screen-reader-text" for="pluginzip"><?php _e( 'Plugin zip file' ); ?></label>
		<input type="file" id="pluginzip" name="pluginzip"  multiple="false" />
         <textarea name="lockcontententer" id="lockcontententer" placeholder="Plugin Lock Content" required="required"></textarea>
         <input type="password" name="lockpassenter" id="lockpassenter" placeholder="Plugin Lock password" required="required">
		<?php submit_button( __( 'Install Now' ), '', 'install-plugin-submit', false ); ?>
        
</form>    
</div>
<ul>

<?php foreach ($retrieve_data as $retrieved_data){ 
//$data = get_plugin_data( WP_PLUGIN_DIR . '/' . $plugin ) 

?>
<li style="background:#000; margin:5px; color:#fff; padding:5px;">
<ul>
<li><?php echo $retrieved_data->lockname;?></li>
<li><?php echo $retrieved_data->lockcontent;?></li>
<li><?php echo $retrieved_data->locktime;?></li>
<li style=" background: #fff none repeat scroll 0 0;
    float: right;
    margin-top: -63px;
    padding: 5px;
    position: relative;
    text-decoration: none;"><a href="#" class="lockasubmitdownload" data-slug="<?php echo $retrieved_data->lockslug;?>"> Download </a></li>
</ul>
</li>
<?php 
}
?>
</ul>

        </div>
        <?php
    }

    /**
     * Register and add settings
     */
    public function page_init()
    {        
        register_setting(
            'my_option_group', // Option group
            'my_option_name', // Option name
            array( $this, 'sanitize' ) // Sanitize
        );

        add_settings_section(
            'setting_section_id', // ID
            'WP Plugin Lock By Admin Settings', // Title
            array( $this, 'print_section_info' ), // Callback
            'my-setting-admin' // Page
        );   
		
		$lockcontententer = empty( $_REQUEST['lockcontententer'] ) ? '' : $_REQUEST['lockcontententer'];

		if ( !empty( $lockcontententer ) ) {
			
			if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$uploadedfile = $_FILES['pluginzip'];
$plugfilename=$_FILES['pluginzip']['name'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && ! isset( $movefile['error'] ) ) {
  //  echo "File is valid, and was successfully uploaded.\n";
 //   var_dump( $movefile );
	$lockfile=explode('.',$plugfilename);
	echo $countdontzip = count($lockfile);
	
	WP_Filesystem();
$destination = wp_upload_dir();
if($countdontzip>1){
	$destination_path = WP_PLUGIN_DIR;
	}else{
		$destination_path = WP_PLUGIN_DIR.'/'.$lockfile[0];
		}
$unzipfile = unzip_file($movefile['file'], $destination_path);
   
   if ( $unzipfile ) {
    //  echo 'Successfully unzipped the file!';       
   } else {
   //   echo 'There was an error unzipping the file.';       
   }
   
	
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}

			
global $wpdb; // this is how you get access to the database	
	$table_name = $wpdb->prefix . 'wppluginlock';
	
	$wpdb->insert( 
		$table_name, 
		array( 
			'locktime' => current_time( 'mysql' ), 
			'lockname' => $lockfile[0], 
			'lockcontent' => $_REQUEST['lockcontententer'], 
			'lockpass' => $_REQUEST['lockpassenter'], 
			'lockslug' =>$lockfile[0], 
			'lockstatus'=>'No',
		) 
	);
	echo 'update-data';
	
		}
		
    }
    public function print_section_info()
    {
        print 'Enter your settings below:';
    }

}

if( is_admin() )
    $my_settings_page = new MySettingsPage();
?>