<!DOCTYPE html>
<html>

<head>
	<!-- Meta Tags -->
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="generator" content="traque" />
	<title>Canvas Signages - Canvas Print</title>
    <meta property="og:title" content="canvassignages" />
    <meta property="og:site_name" content="canvassignages" />
    <meta property="og:url" content="www.canvassignages.com" />
    <meta property="og:type" content="website">
    <meta property="og:image" content="www.canvassignages.com/images/social.jpg" />
    <meta property="og:description" content="Short Description of Site" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet"> 

    <!-- Stylesheets -->
    <link rel="shortcut icon" href="images/favicon.png" />
	<link rel="stylesheet" type="text/css" href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/css/style.css">
	<link rel="stylesheet" type="text/css" href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/css/editor.css">
	<link rel="stylesheet" type="text/css" href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/css/before-after.css">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- css added for development -->
	<link rel="stylesheet" type="text/css" href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/css/custom.css">

	<!--[if lt IE 9]>
      	<script src="js/html5.js"></script>
    <![endif]-->

   
<body>

	<!-- Editor Header -->
	<div class="editor-header">
		<div class="col-lg-4 col-md-3 col-sm-4 col-xs-12">
			<div class="logo">
				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/small-logo.png" alt="Logo">
			</div>
		</div>
		<div class="col-lg-4 col-md-5 col-sm-4 col-xs-12 no-padding">
			<div class="editor-middle-text dropdown">
				Custom Canvas Prints <a href="#" class="dropdown-toggle" data-toggle="dropdown">(8x8” + $30.67)<i class="fa fa-angle-down" aria-hidden="true"></i></a>
				<ul class="dropdown-menu">
				    <li>
				    	8X8” Thin wrap gallery (0.754)
				    	<div class="pull-right">
				    		<a href="javascript:void(0)">$6.69</a>
				    		<a href="#" class="icon"><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/edit.png" alt="Edit"></a>
				    	</div>
				    </li>
				    <li>
				    	<span>Black Frame </span>
				    	<div class="pull-right">
				    		<a href="javascript:void(0)">$9.99</a>
				    		<a href="#" class="icon"><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove.png" alt="Remove"></a>
				    	</div>
				    </li>
				    <li>
				    	<span>Minor Photo Retouching </span>
				    	<div class="pull-right">
				    		<a href="javascript:void(0)">$9.99</a>
				    		<a href="#" class="icon"><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove.png" alt="Remove"></a>
				    	</div>
				    </li>
				    <li>
				    	<span>Lamination </span>
				    	<div class="pull-right">
				    		<a href="javascript:void(0)">$4.00</a>
				    		<a href="#" class="icon"><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove.png" alt="Remove"></a>
				    	</div>
				    </li>
				    <li class="subtotal">
				    	<span class="title">Subtotal</span>
				    	<span class="price">$30.67</span>
				    </li>
				</ul>
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 no-padding">
			<div class="editor-top-menu">
				<ul class="list-unstyled">
					<li>
						<a href="#"  data-toggle="modal" data-target=".how-to-design-video">How to Design?</a>
					</li>
					<li class="order">
						<a href="javascript:void(0)">Order Now</a>
					</li>
				</ul>
			</div>
		</div>
	</div>

	<!-- How To Design Popup Video -->
	<div class="modal fade how-to-design-video" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	  	<div class="modal-dialog">
	    	<div class="modal-content">
	    		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          			<span aria-hidden="true">Minimize</span><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/minimize-icon.png" alt="Minimize Icon">
        		</button>
	      		<iframe width="700" height="500" src="https://www.youtube.com/embed/uXATjvr_rl4" frameborder="0" allowfullscreen></iframe>
	    	</div>
	  	</div>
	</div>


	<!-- Editor Main Content -->
	<div class="editor-main-content">
		
		<!-- Editor Sidebar -->
		<div class="editor-sidebar">
			<ul class="list-unstyled">
				<li>
					<a href="javascript:void(0)" class="link">
						<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/size.png" alt="Editor Icon">
						<span>Size</span>
					</a>
					<div class="sidebar-content size-prize ">
						<ul class="nav nav-tabs" role="tablist">
						    <li role="presentation" class="">
						    	<a href="#Rolled-Cannvas" role="tab" data-toggle="tab" aria-expanded="true">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Rolled-Canvas.jpg" alt="Size">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-image" alt="Select Image">
						    		<span>Rolled <br>Canvas</span>
						    	</a>
						    </li>
						    <li role="presentation" class="active">
						    	<a href="#Thin-Gallery " role="tab" data-toggle="tab" aria-expanded="false">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Thin-Gallery.jpg" alt="Size">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-image" alt="Select Image">
						    		<span>Thin Gallery Wrap (0.75")</span>		
						    	</a>
						    </li>
						    <li role="presentation" class="">
						    	<a href="#Thick-Gallery " role="tab" data-toggle="tab" aria-expanded="false">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Thick-Gallery.jpg" alt="Size">
						    		<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-image" alt="Select Image">
						    		<span>Thick Gallery Wrap (1.5")</span>		
						    	</a>
						    </li>
						</ul>
						<div class="tab-content">
						    <div role="tabpanel" class="tab-pane" id="Rolled-Cannvas">
						    	<div class="price-size-table">
							    	<ul class="list-unstyled">
							    		<li class="sub-title">
							    			<span class="size-title">Select size</span>
							    			<span class="discount-title">discounted prize</span>
							    		</li>
							    		<li>
							    			<input id="option1" name="selector" checked="check" type="radio">
										    <label for="option1">8x8"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $6.69
										    </span>
							    		</li>
							    		<li>
							    			<input id="option2" name="selector" type="radio">
										    <label for="option2">8x12"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $12.61
										    </span>
							    		</li>
							    		<li>
							    			<input id="option3" name="selector" type="radio">
										    <label for="option3">9x9"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $10.07
										    </span>
							    		</li>
							    		<li>
							    			<input id="option4" name="selector" type="radio">
										    <label for="option4">16x20"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $28.41
										    </span>
							    		</li>
							    		<li>
							    			<input id="option5" name="selector" type="radio">
										    <label for="option5">18x36"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $50.97
										    </span>
							    		</li>
							    		<li class="custom-size"> 
							    			<input id="option6" name="selector" type="radio">
										    <label for="option6">Custom Size</label>
										    <div class="check"></div>
										    <div class="select-box">
											    <select>
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											    x
											    <select>
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											</div>
							    		</li>
							    		
							    	</ul>
							    </div>
						    </div>
						    <div role="tabpanel" class="tab-pane active" id="Thin-Gallery">
						    	<div class="price-size-table">
							    	<ul class="list-unstyled">
							    		<li class="sub-title">
							    			<span class="size-title">Select size</span>
							    			<span class="discount-title">discounted prize</span>
							    		</li>
							    		<li>
							    			<input id="option7" name="selector1" checked="check" data-w="8" data-h="8"  type="radio">
										    <label for="option7">8x8"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $6.69
										    </span>
							    		</li>
							    		<li>
							    			<input id="option8" name="selector1" data-w="8" data-h="12" type="radio">
										    <label for="option8">8x12"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $12.61
										    </span>
							    		</li>
							    		<li>
							    			<input id="option9" name="selector1" data-w="9" data-h="9" type="radio">
										    <label for="option9">9x9"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $10.07
										    </span>
							    		</li>
							    		<li>
							    			<input id="option10" name="selector1" data-w="16" data-h="12" type="radio">
										    <label for="option10">16x20"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $28.41
										    </span>
							    		</li>
							    		<li>
							    			<input id="option11" name="selector1" data-w="18" data-h="36" type="radio">
										    <label for="option11">18x36"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $50.97
										    </span>
							    		</li>
							    		<li class="custom-size"> 
							    			<input id="option12" name="selector1" data-w="custom" data-h="custom" type="radio">
										    <label for="option12">Custom Size</label>
										    <div class="check"></div>
										    <div class="select-box">
											    <select disabled="true" class="disable">
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											    x
											    <select disabled="true" class="disable">
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											</div>
							    		</li>
							    	</ul>
							    </div>
						    </div>
						    <div role="tabpanel" class="tab-pane" id="Thick-Gallery">
						    	<div class="price-size-table">
							    	<ul class="list-unstyled">
							    		<li class="sub-title">
							    			<span class="size-title">Select size</span>
							    			<span class="discount-title">discounted prize</span>
							    		</li>
							    		<li>
							    			<input id="option13" name="selector2" type="radio">
										    <label for="option13">8x8"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $6.69
										    </span>
							    		</li>
							    		<li>
							    			<input id="option14" name="selector2" checked="check" type="radio">
										    <label for="option14">8x12"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $12.61
										    </span>
							    		</li>
							    		<li>
							    			<input id="option15" name="selector2" type="radio">
										    <label for="option15">9x9"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $10.07
										    </span>
							    		</li>
							    		<li>
							    			<input id="option16" name="selector2" type="radio">
										    <label for="option16">16x20"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $28.41
										    </span>
							    		</li>
							    		<li>
							    			<input id="option17" name="selector2" type="radio">
										    <label for="option17">18x36"</label>
										    <div class="check"></div>
										    <span class="price">
										    	<strike>$37.09</strike> $50.97
										    </span>
							    		</li>
							    		<li class="custom-size"> 
							    			<input id="option18" name="selector2" type="radio">
										    <label for="option18">Custom Size</label>
										    <div class="check"></div>
										    <div class="select-box">
											    <select>
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											    x
											    <select>
											    	<option>8</option>
											    	<option>9</option>
											    	<option>10</option>
											    	<option>11</option>
											    	<option>12</option>
											    </select>
											</div>
							    		</li>
							    	</ul>
							    </div>
						    </div>
						</div>
					</div>
				</li>
				<li>
					<a href="javascript:void(0)" class="link">
						<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/image.png" alt="Editor Icon">
						<span>Image</span>
					</a>
					<div class="sidebar-content image">
						<button type="button" class="button medium blue" data-toggle="modal" data-target="#photo-uplopad">
						  	Upload Photos
						</button>
						<div class="upload-photo-icon">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/upload-photo-icon.png" alt="upload photo icon">						
						</div>
						<div class="uploaded-image">
							<div class="uploaded-photo-box select">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
				  			</div>
				  			<div class="uploaded-photo-box">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
				  			</div>
				  			<div class="uploaded-photo-box">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
				  			</div>
				  			<div class="uploaded-photo-box">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
				  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
				  			</div>
						</div>
					</div>

				</li>
				<li>
					<a href="javascript:void(0)" class="link">
						<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/style.png" alt="Editor Icon">
						<span>Style</span>
					</a>
					<div class="sidebar-content style">
						<ul class="nav nav-tabs">
						  	<li class="active"><a data-toggle="tab" href="#Wrap-Border">Wrap/Border</a></li>
						  	<li><a data-toggle="tab" href="#Frames">Frames</a></li>
						</ul>

						<div class="tab-content">
						  	<div id="Wrap-Border" class="tab-pane fade in active">
						    	<ul class="list-unstyled">
						    		<li class="active">
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/photo-wrap.jpg" alt="Style Image">
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Photo Wrap</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/mirror-image.jpg" alt="Style Image">
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Mirror Image</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/color-wrap.jpg" alt="Style Image">
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Color Wrap</span>
						    			</a>
						    		</li>
						    	</ul>
						  	</div>
						  	<div id="Frames" class="tab-pane fade">
						    	<ul class="list-unstyled">
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/black-frame.jpg" alt="Style Image">
						    				<span class="frame-size">1"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Black - $9.99</span>
						    			</a>
						    		</li>
						    		<li class="active">
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/brown-frame.jpg" alt="Style Image">
						    				<span class="frame-size">1"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Brown - $9.99</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/cofee-frame.jpg" alt="Style Image">
						    				<span class="frame-size">1"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Cofee Net - $9.99</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/black-silver-frame.jpg" alt="Style Image">
						    				<span class="frame-size">1"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Black & Silver - $9.99</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Marron-Gold-frame.jpg" alt="Style Image">
						    				<span class="frame-size">0.5"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Marron & Gold - $9.99</span>
						    			</a>
						    		</li>
						    		<li>
						    			<a href="javascript:void(0)">
						    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/black-thin-frame.jpg" alt="Style Image">
						    				<span class="frame-size">0.5"</span>
						    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
						    				<span>Black - $9.99</span>
						    			</a>
						    		</li>
						    	</ul>
						  	</div>
						</div> 
					</div>
				</li>
				<li>
					<a href="javascript:void(0)" class="link">
						<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/text.png" alt="Editor Icon">
						<span>Text</span>
					</a>
					<div class="sidebar-content text">
						<div class="form-group">
						  	<label for="comment">Add Text</label>
						  	<textarea class="form-control" rows="4" id="comment" placeholder="Type Here"></textarea>
						  	<button class="button medium blue">Add</button>
						</div> 
					</div>
				</li>
				<li>
					<a href="javascript:void(0)" class="link">
						<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/addon.png" alt="Editor Icon">
						<span>Addon</span>
					</a>
					<div class="sidebar-content addon">
						<div class="panel-group" id="accordion">
						  	<div class="panel panel-default">
						    	<div class="panel-heading">
						      		<div class="panel-title">
						        		<a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
						        		Hardware
						        		<i class="fa fa-angle-right pull-right" aria-hidden="true"></i>
						        		</a>
						      		</div>
						    	</div>
						    	<div id="collapse1" class="panel-collapse collapse in">
						      		<div class="panel-body">
						      			<ul class="list-unstyled">
								    		<li class="active">
								    			<a href="javascript:void(0)">
								    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Hooks.jpg" alt="Style Image">
								    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
								    				<span>Hooks for Hanging (Free)</span>
								    			</a>
								    		</li>
								    		<li>
								    			<a href="javascript:void(0)">
								    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Sawtooth.jpg" alt="Style Image">
								    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
								    				<span>Sawtooth Hanger (Free)</span>
								    			</a>
								    		</li>
								    	</ul>
						      		</div>
						    	</div>
						  	</div>
						  	<div class="panel panel-default">
						    	<div class="panel-heading">
						      		<div class="panel-title">
						        		<a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="collapsed">
						        		Photo Filters
						        		<i class="fa fa-angle-right pull-right" aria-hidden="true"></i>
						        		</a>
						      		</div>
						    	</div>
						    	<div id="collapse2" class="panel-collapse collapse">
						      		<div class="panel-body">
						      			<ul class="list-unstyled">
								    		<li class="active">
								    			<a href="javascript:void(0)">
								    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Original.jpg" alt="Style Image">
								    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
								    				<span>Original (Free)</span>
								    			</a>
								    		</li>
								    		<li>
								    			<a href="javascript:void(0)">
								    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/Sepia-free.jpg" alt="Style Image">
								    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
								    				<span>Sepia (Free)</span>
								    			</a>
								    		</li>
								    		<li>
								    			<a href="javascript:void(0)">
								    				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/GreyScale.jpg" alt="Style Image">
								    				<img class="select-check" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" alt="Select Check">
								    				<span>GreyScale (Free)</span>
								    			</a>
								    		</li>
								    	</ul>
						      		</div>
						    	</div>
						  	</div>
						  	<div class="panel panel-default">
						    	<div class="panel-heading">
						      		<div class="panel-title">
						        		<a data-toggle="collapse" data-parent="#accordion" href="#collapse3" class="collapsed">
						        		Photo Retouching
						        		<i class="fa fa-angle-right pull-right" aria-hidden="true"></i>
						        		</a>
						      		</div>
						    	</div>
							    <div id="collapse3" class="panel-collapse collapse">
							      	<div class="panel-body">
							      		<div class="photo-retouching">
							      			<div class="radio-group">
								      			<input id="no-retouch" name="selector5" type="radio" checked="check">
												<label for="no-retouch">No Image Retouch</label>
												<div class="check"></div>
											</div>
											<div class="radio-group">
												<input id="minor-retouch" name="selector5" type="radio" >
												<label for="minor-retouch">Minor Image Retouch ($9.99)</label>
												<div class="check"></div>
												<div id="minor-retouch">
													<ul>
														<li>Exposure & Color Correction</li>
														<li>Image Sharpening</li>
														<li>Red Eye Fix</li>
														<li>Straighten and Crop</li>
														<li>Remove Blemishes</li>
														<li>Soften Facial Lines</li>
														<li>Dust/Scratch Removal</li>
													</ul>
												</div>
											</div>
											<div class="radio-group">
												<input id="major-retouch" name="selector5" type="radio">
												<label for="major-retouch">Major Image Retouch ($19.99)</label>
												<div class="check"></div>
												<div id="major-retouch">
													<div class="form-group">
													  	<textarea class="form-control" rows="4" id="comment" placeholder="Requirement for Retouching"></textarea>
													</div>
												</div>
											</div>
							      		</div>

							      	</div>
							    </div>
							</div>
							<div class="panel panel-default">
						    	<div class="panel-heading">
						      		<div class="panel-title">
						        		<a data-toggle="collapse" data-parent="#accordion" href="#collapse4" class="collapsed">
						        		Lamination
						        		<i class="fa fa-angle-right pull-right" aria-hidden="true"></i>
						        		</a>
						      		</div>
						    	</div>
							    <div id="collapse4" class="panel-collapse collapse">
							    	<div class="panel-body">
								      	<div class="photo-retouching">
							      			<div class="radio-group">
								      			<input id="yes" name="selector2" type="radio" checked="check">
												<label for="yes">Yes ($4.00)</label>
												<div class="check"></div>
											</div>	
											<div class="radio-group">
								      			<input id="no" name="selector2" type="radio">
												<label for="no">No</label>
												<div class="check"></div>
											</div>	
										</div>
									</div>
							    </div>
							</div>
						</div> 
					</div>
				</li>
			</ul>
		</div>

		<!-- Editor Screen -->
		<div class="edit-screen-container">

			<div class="edit-screen">
				 <div class="loading_img">
					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/loading.gif" alt="">
				</div>
				<div class="edit-screen-outer">
					<!-- Main canvas area -->
					<div class="image canvasWrap">

						
						<!-- <img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/edit-screen-image.jpg" alt="Edit Screen"> -->
						<!-- <div class="edit-text">
							DRAG PHOTO HERE
						</div> -->
						<canvas id="mainCanvas" width="500" height="500"></canvas>
					</div>
				</div>
				<div class="design-view-container">
					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/design-view.jpg">
				</div>
				<div class="view-menu">
					<ul class="list-unstyled">
						<li class="active">
							<a class="room-view" href="#">Design View</a>
						</li>
						<li>
							<a class="design-view" href="#">Room View</a>
						</li>
					</ul>
				</div>
			</div>

			<div class="edit-menu">
				<ul class="list-unstyled">
					<li class="active">
						<label><span>Undo</span></label>
						<a href="javascript:void(0)">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/undo.png" alt="Edit Icon">
						</a>
					</li>
					<li>
						<label><span>Redo</span></label>
						<a href="javascript:void(0)">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/redo.png" alt="Edit Icon">
						</a>
					</li>
					<li>

						<label><span>Save</span></label>
						<a href="http://onlinedevserver.biz/dev/canvassignages/liveeditor/index/save">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/save.png" alt="Edit Icon">
						</a>
					</li>
					<li class="preview-button">
						<label><span>3D Preview</span></label>
						<a href="#" >
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/3D.png" alt="Edit Icon">
						</a>
						<div class="preview-box">
							<ul class="list-unstyled">
								<li class="main-title">3D Preview</li>
								<li>
									<a href="javascript:void(0)">
										<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/preview-top-left.png" alt="Preview Image">
									</a>
									<div class="preview-title">Top Left</div>
								</li>
								<li>
									<a href="javascript:void(0)">
										<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/preview-top-right.png" alt="Preview Image">
									</a>
									<div class="preview-title">Top Right</div>
								</li>
								<li>
									<a href="javascript:void(0)">
										<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/preview-left-bottom.png" alt="Preview Image">
									</a>
									<div class="preview-title">Left Bottom</div>
								</li>
								<li>
									<a href="javascript:void(0)">
										<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/preview-right-bottom.png" alt="Preview Image">
									</a>
									<div class="preview-title">Right Bottom</div>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<label><span>Zoom In</span></label>
						<a href="javascript:void(0)">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/zoom-in.png" alt="Edit Icon">
						</a>
					</li>
					<li>
						<label><span>Zoom Out</span></label>
						<a href="javascript:void(0)">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/zoom-out.png" alt="Edit Icon">
						</a>
					</li>
					<li>
						<label><span>Help</span></label>
						<a href="javascript:void(0)">
							<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/help.png" alt="Edit Icon">
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>


	<!-- Photo Upload Popup -->
	<div class="modal fade photo-upload-popup" id="photo-uplopad" tabindex="-1" role="dialog" aria-labelledby="photo-uplopad" aria-hidden="true">
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
      			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          			<span aria-hidden="true">Minimize</span><img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/minimize-icon.png" alt="Minimize Icon">
        		</button>
	      		<div class="modal-body">
	        		<ul class="nav nav-tabs" role="tablist">
					  	<li class="nav-item active">
					    	<a class="nav-link active" data-toggle="tab" href="#upload-photo" role="tab">Upload Photo</a>
					  	</li>
					  	<li class="nav-item">
					    	<a class="nav-link" data-toggle="tab" href="#my-photo" role="tab">My Photo</a>
					  	</li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
					  	<div class="tab-pane active" id="upload-photo" role="tabpanel">
					  		<div class="upload-photo-main">
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
						  				<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-computer.png" alt="Upload Icon">
						  					<span>My Computer</span>
						  				</a>
						  			</div>
					  			</div>
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
						  				<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/facebook.png" alt="Upload Icon">
						  					<span>Facebook</span>
						  				</a>
						  			</div>
					  			</div>
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
						  				<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/instagram.png" alt="Upload Icon">
						  					<span>Instagram</span>
						  				</a>
						  			</div>
					  			</div>
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
						  				<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/flickr.png" alt="Upload Icon">
						  					<span>Flickr</span>
						  				</a>
						  			</div>
					  			</div>
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
					  					<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/google-photo.png" alt="Upload Icon">
						  					<span>Google Photo</span>
						  				</a>
						  			</div>
					  			</div>
					  			<div class="upload-photo-box">
					  				<div class="upload-photo-box-inner">
						  				<a href="javascript:void(0)">
						  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/photo-bucket.png" alt="Upload Icon">
						  					<span>Photo Bucket</span>
					  					</a>
					  				</div>
					  			</div>
					  		</div>
					  	</div>
					  	<div class="tab-pane" id="my-photo" role="tabpanel">
					  		<div class="my-photos">
					  			<div class="my-photos-image-box select">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  			<div class="my-photos-image-box">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/remove-white.png" class="remove" alt="Remove"> 
				  					<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/select-check.png" class="select-check" alt="Select Check">
					  				<img src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/images/my-photos-image.jpg" alt="My Photos">
					  			</div>
					  		</div>
					  		<div class="button-group">
					  			<div class="pull-left">
					  				<button value="" name="" class="button medium border">Select All</button>
					  				<button value="" name="" class="button medium border">Delete All</button>
					  			</div>
					  			<div class="pull-right">
					  				<button value="" name="" class="button medium blue">Add Selected Photos</button>
					  			</div>
					  		</div>
					  	</div>
					</div>
	      		</div>
	    	</div>
	  	</div>
	</div>
<form action="http://onlinedevserver.biz/dev/canvassignages/liveeditor/index/save" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="nom">Name</label>
       <input type="hidden" id="name" name="name" value="sss"/>
     </li>
     <li>
        <input type="submit" value="Enregistrer" />
    </li>
  </ul>
 </fieldset>
</form>
	

	<!-- Javascript -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
	<!-- jquery ui -->
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script type="text/javascript" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/js/bootstrap.js"></script>	
	<!-- fabric -->
	<script src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/js/fabric.min.js"></script>
	<script type="text/javascript" src="http://onlinedevserver.biz/dev/canvassignages/liveeditor/js/custom_editor.js"></script>
	<script type="text/javascript">

	// Sidebar JS

	$(".editor-sidebar li a").click(function() {

     	$(this).parent().addClass('selected').siblings().removeClass('selected');
    });
	$(document).click(function(e){
	    var targetbox = $('.editor-sidebar li');
	    if(!targetbox.is(e.target) && targetbox.has(e.target).length === 0){
	        $('.editor-sidebar li').removeClass("selected");
	    }
	});

	// Popup Photo Select Js
	$(".my-photos-image-box").click(function() {
	 	$(this).addClass('select').siblings().removeClass('select');
    });

	// Sidebar Photo Select Js
	$(".uploaded-photo-box").click(function() {
	 	$(this).addClass('select').siblings().removeClass('select');
    });
    
	// Sidebar Style Photo Select Js
	$(".sidebar-content.style .tab-content li").click(function() {
	 	$(this).addClass('active').siblings().removeClass('active');
    });
    
    // Sidebar Addon Photo Select Js
	$(".sidebar-content.addon .panel-body li").click(function() {
	 	$(this).addClass('active').siblings().removeClass('active');
    });

    //View Menu Js 
    $(".view-menu li").click(function() {
	 	$(this).addClass('active').siblings().removeClass('active');
    });
    $(".view-menu a.design-view").click(function() {
	 	$('body').addClass('design-view-open');
    });
    $(".view-menu a.room-view").click(function() {
	 	$('body').removeClass('design-view-open');
    });

	// 3D Prview Icon JS
	$(".preview-button").click(function() {
	 	$(this).addClass('active').siblings().removeClass('active');
    });
    $(document).click(function(e){
	    var targetbox = $('.preview-button');
	    if(!targetbox.is(e.target) && targetbox.has(e.target).length === 0){
	        $('.preview-button').removeClass("active");
	    }
	});
	</script>




</body>
</html>


	

    

